use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::context::*;
use crate::manifests::{validate_artifacts, Artifact, Component, Target};
use crate::model;

pub(crate) fn render_components(components: &[Component]) -> String {
    let mut components = components.to_vec();
    components.sort_by(|a, b| a.path.cmp(&b.path));
    let mut output = String::from(
        "<!-- Generated by `cargo xtask docs`; do not edit. -->\n\n\
         # Component inventory\n\n\
         | Manifest | Kind | Workspace | Artifact disposition | Role | Required gate |\n\
         |---|---|---|---|---|---|\n",
    );
    for component in components {
        output.push_str(&format!(
            "| `{}` | {} | {} | `{}` | {} | {} |\n",
            component.path,
            component.kind,
            component.workspace,
            component.artifact,
            component.role,
            component.gate
        ));
    }
    output
}

pub(crate) fn load_build_inputs(root: &Path) -> Result<BTreeMap<String, String>, String> {
    let path = root.join(BUILD_INPUTS);
    let text = fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut inputs = BTreeMap::new();
    for (index, raw) in text.lines().enumerate() {
        let line = raw.split('#').next().unwrap_or_default().trim();
        if line.is_empty() {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("{}:{}: expected KEY=value", path.display(), index + 1))?;
        if key.is_empty()
            || !key
                .bytes()
                .all(|byte| byte.is_ascii_uppercase() || byte == b'_' || byte.is_ascii_digit())
            || value.is_empty()
        {
            return Err(format!(
                "{}:{}: invalid build input",
                path.display(),
                index + 1
            ));
        }
        if inputs.insert(key.to_owned(), value.to_owned()).is_some() {
            return Err(format!("{}:{}: duplicate {key}", path.display(), index + 1));
        }
    }
    for required in [
        "LIMINE_REPOSITORY",
        "LIMINE_REF",
        "LIMINE_REVISION",
        "OVMF_TAG",
        "OVMF_SHA256",
    ] {
        if !inputs.contains_key(required) {
            return Err(format!("{} is missing {required}", path.display()));
        }
    }
    Ok(inputs)
}

fn render_build_inputs(inputs: &BTreeMap<String, String>) -> String {
    let mut output = String::from(
        "<!-- Generated by `cargo xtask docs`; do not edit. -->\n\n\
         # Immutable build inputs\n\n\
         | Input | Pinned value |\n\
         |---|---|\n",
    );
    for (key, value) in inputs {
        output.push_str(&format!("| `{key}` | `{value}` |\n"));
    }
    output
}

fn render_targets(targets: &[Target]) -> String {
    let mut output = String::from(
        "<!-- Generated by `cargo xtask docs`; do not edit. -->\n\n\
         # Supported target and feature matrix\n\n\
         | Target | Triple | Status | Features | Artifact | Required evidence |\n\
         |---|---|---|---|---|---|\n",
    );
    for target in targets {
        output.push_str(&format!(
            "| {} | `{}` | {} | `{}` | {} | {} |\n",
            target.name,
            target.triple,
            target.status,
            target.features,
            target.artifact,
            target.evidence
        ));
    }
    output
}

fn render_artifacts(artifacts: &[Artifact]) -> String {
    let mut artifacts = artifacts.to_vec();
    artifacts.sort_by(|a, b| a.name.cmp(&b.name));
    let mut output = String::from(
        "<!-- Generated by `cargo xtask docs`; do not edit. -->\n\n\
         # Shipped-image and artifact provenance\n\n\
         This table defines build recipes and selection rules. Per-build SHA-256 values are retained in the evidence location named by each row; generated outputs are not assigned static hashes. Raspberry Pi boot firmware is an external platform/HIL prerequisite rather than a repository-produced image, so its exact revision and hashes belong in retained HIL evidence.\n\n\
         | Artifact | Platform | Status | Format | Producer | Output / identity | Selection rule | Immutable inputs | Hash evidence |\n\
         |---|---|---|---|---|---|---|---|---|\n",
    );
    for artifact in artifacts {
        output.push_str(&format!(
            "| {} | {} | {} | {} | `{}` | `{}` | {} | {} | {} |\n",
            artifact.name,
            artifact.platform,
            artifact.status,
            artifact.format,
            artifact.producer,
            artifact.output,
            artifact.selection,
            artifact.immutable_inputs,
            artifact.hash_evidence
        ));
    }
    output
}

fn render_abi_entries(output: &mut String, title: &str, entries: &[kernel_abi::AbiEntry]) {
    output.push_str(&format!(
        "## {title}\n\n| ID | Name | Availability |\n|---:|---|---|\n"
    ));
    for entry in entries {
        output.push_str(&format!(
            "| {} | `{}` | {} |\n",
            entry.id, entry.name, entry.availability
        ));
    }
    output.push('\n');
}

fn render_abi() -> String {
    let mut output = format!(
        "<!-- Generated by `cargo xtask docs`; do not edit. -->\n\n\
         # axiomos userspace ABI v{}.{}\n\n\
         This catalog contains only interfaces dispatched by shipped kernels. Reserved syscall/BPF numbers, verifier-known but undispatched helpers, and `verifier-cost` instrumentation are not supported ABI.\n\n",
        kernel_abi::AXIOMOS_ABI_MAJOR,
        kernel_abi::AXIOMOS_ABI_MINOR
    );
    render_abi_entries(&mut output, "Syscalls", kernel_abi::SUPPORTED_SYSCALLS);
    render_abi_entries(
        &mut output,
        "BPF commands",
        kernel_abi::SUPPORTED_BPF_COMMANDS,
    );
    render_abi_entries(
        &mut output,
        "BPF map types",
        kernel_abi::SUPPORTED_BPF_MAP_TYPES,
    );
    render_abi_entries(
        &mut output,
        "BPF helpers",
        kernel_abi::SUPPORTED_BPF_HELPERS,
    );
    render_abi_entries(
        &mut output,
        "BPF attach types",
        kernel_abi::SUPPORTED_BPF_ATTACH_TYPES,
    );
    output.pop();
    output
}

fn check_or_write(path: &Path, expected: &str, check: bool) -> Result<(), String> {
    if check {
        let actual = fs::read_to_string(path)
            .map_err(|e| format!("{}: {e}; run `cargo xtask docs`", path.display()))?;
        if actual != expected {
            return Err(format!(
                "{} is stale; run `cargo xtask docs`",
                path.display()
            ));
        }
    } else {
        fs::write(path, expected).map_err(|e| format!("{}: {e}", path.display()))?;
        println!("updated {}", path.display());
    }
    Ok(())
}

pub(crate) fn check_or_write_docs(
    root: &Path,
    model: &model::RepositoryModel,
    check: bool,
) -> Result<(), String> {
    validate_artifacts(&model.artifacts, &model.targets)?;
    check_or_write(
        &root.join(GENERATED_COMPONENTS),
        &render_components(&model.components),
        check,
    )?;
    check_or_write(
        &root.join(GENERATED_BUILD_INPUTS),
        &render_build_inputs(&model.build_inputs),
        check,
    )?;
    check_or_write(
        &root.join(GENERATED_TARGETS),
        &render_targets(&model.targets),
        check,
    )?;
    check_or_write(
        &root.join(GENERATED_ARTIFACTS),
        &render_artifacts(&model.artifacts),
        check,
    )?;
    check_or_write(&root.join(GENERATED_ABI), &render_abi(), check)?;
    Ok(())
}
