[package]
name = "rk-bridge-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
rk_bridge = { path = ".." }

[profile.release]
debug = true

[[bin]]
name = "event_stream"
path = "fuzz_targets/event_stream.rs"
test = false
doc = false
bench = false
